version: "3"
services:
  ancillary-proxy-server:
    build: 
      dockerfile: ./server/Dockerfile
      context: ./
    volumes:
      - ./config:/config:rw
    ports:
      - 102:102
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "1g"
        max-file: "3"
        labels: "ancillary-proxy"
  client:
    build: 
      dockerfile: ./client/Dockerfile
      context: ./
    volumes:
      - ./config:/config:rw
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "1g"
        max-file: "1"
        labels: "dummy-client"
volumes:
  config:
