version: "3"
services:
  ancillary-proxy-server:
    build: 
      dockerfile: ./server/Dockerfile
      context: ./
    volumes:
      - ./config:/config:rw
    ports:
      - 102:102
      - 61850:61850
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "1g"
        max-file: "3"
        labels: "ancillary-proxy"
    networks:
      - default
      - grpc
  client:
    build: 
      dockerfile: ./client/Dockerfile
      context: ./
    volumes:
      - ./config:/config:rw
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "1g"
        max-file: "1"
        labels: "dummy-client"
    cap_add:
      - SYS_PTRACE
volumes:
  config:
networks:
  grpc:
    driver: bridge
